# -*- coding: utf-8 -*-
"""Average_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlRyWvjw5KLA5S69r_5vBrhX6ozSlNMQ
"""

a = input().split(" ")
N1, N2, N3, N4 = float(a[0]), float(a[1]), float(a[2]), float(a[3])
avg = ((N1*2) + (N2*3) + (N3*4) + (N4*1)) / 10
print(f"Media: {avg:.1f}")

if avg >= 7.0:
    print(f"Aluno aprovado.")
elif avg < 5.0:
    print(f"Aluno reprovado.")
elif (5.0 <= avg) and (avg < 7.0):
    print(f"Aluno em exame.")
    n = float(input())
    print(f"Nota do exame: {n}")
    avg2 = (avg + n) / 2
    if avg2 >= 5.0:
        print(f"Aluno aprovado.")
    else:
        print(f"Aluno reprovado.")
    print(f"Media final: {avg2:.1f}")