# -*- coding: utf-8 -*-
"""even.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlRyWvjw5KLA5S69r_5vBrhX6ozSlNMQ
"""

for n in range(1, 101):
    if n % 2 == 0:
        print(n)