# -*- coding: utf-8 -*-
"""Positives and Average.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlRyWvjw5KLA5S69r_5vBrhX6ozSlNMQ
"""

count=0
sum=0.0
for i in range(1,7):
    n = float(input())
    if(n>0):
        sum = sum + n
        count=count+1
average = sum/count
print(f"{count} valores positivos")
print(f"{average:0.1f}")