# -*- coding: utf-8 -*-
"""reverseWord.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlRyWvjw5KLA5S69r_5vBrhX6ozSlNMQ
"""

word = input("Input a word: ")
for char in range(len(word) - 1, -1, -1):
    print(word[char], end="")

print("\n")