# -*- coding: utf-8 -*-
"""simpleSort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlRyWvjw5KLA5S69r_5vBrhX6ozSlNMQ
"""

a = input().split(" ")
X, Y, Z = int(a[0]), int(a[1]), int(a[2])

if X > Y:
    if X > Z:
        if Y > Z:
            print(Z)
            print(Y)
            print(X)
            print(end='\n')
            print(X)
            print(Y)
            print(Z)
    else:
        print(Y)
        print(X)
        print(Z)
        print(end='\n')
        print(X)
        print(Y)
        print(Z)
elif Y > Z:
    if Z > X:
        print(X)
        print(Z)
        print(Y)
        print(end='\n')
        print(X)
        print(Y)
        print(Z)
    else:
        print(Z)
        print(X)
        print(Y)
        print(end='\n')
        print(X)
        print(Y)
        print(Z)
else:
    print(Z)
    print(Y)
    print(X)
    print(end='\n')
    print(X)
    print(Y)
    print(Z)