# -*- coding: utf-8 -*-
"""taxes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlRyWvjw5KLA5S69r_5vBrhX6ozSlNMQ
"""

a = float(input())

if 0.00 < a < 2000.00:
    print("Isento")
elif 2000.00 < a < 3000.00:
    b = a-2000.00
    c = b * 0.08
    print(f"R$ {c:.2f}")
elif 3000.00 < a < 4500.00:
    b = a-3000.00
    c = (b * 0.18) + (1000 * 0.08)
    print(f"R$ {c:.2f}")
else:
    b = a - 4500.00
    c = (b * 0.28) + (1500.00 * 0.18) + (1000 * 0.08)
    print(f"R$ {c:.2f}")