# -*- coding: utf-8 -*-
"""The Greatest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlRyWvjw5KLA5S69r_5vBrhX6ozSlNMQ
"""

x = input().split(" ")
a,b,c = int(x[0]), int(x[1]), int(x[2])

g = (a+b+abs(a-b))/2
f = (g+c+abs(g-c))/2

print(f"{int(f)} eh o maior")