# -*- coding: utf-8 -*-
"""Time Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlRyWvjw5KLA5S69r_5vBrhX6ozSlNMQ
"""

N = int(input())

hour = N // 3600
N %= 3600
minutes = N // 60
seconds = N % 60

print(f"{hour}:{minutes}:{seconds}")